### ISSUE TITLE
Feature request: General literate programming support

### ISSUE THREAD

**Issue by devendra-ghate** [CDSoft/abp#1]
I see that many diagram creation methods are already supported. I expect literate `python` and `bash` will also be included in due time. It is present in `pp` for both code blocks and inline code snippets.

I have a request that general support for **any** language can be provided along the lines of this discussion.

https://github.com/jgm/pandoc/issues/656

I am interested in support for `julia`. I would like to be able to include `julia` code in a code block from a file (which can be done presently) and then have it displayed. It should also be executed and the output should be included in the markdown file. Output may be some text to be included in a separate code block OR an image generated by the code.

There should be option to 

- only display the code,
- display the code and the output, and
- display only the output of the code.

Since I have no idea regarding the complexity involved in achieving this, please take this only as a wishlist from a user of `pp` and future user of `abp`.

**Comment by CDSoft** [comment]
abp implements generic mechanisms to call scripts and get either stdout or any image. There are some shortcuts but you can define your own shortcuts (and share them ;-).

e.g. to run a Julia script and replace the source block by its result (stdout):

    ```{cmd=julia}
    println("Hello World!")
    ```

will produce a block block containing `Hello World!`
(see https://cdsoft.fr/abp/#scripts)

And to add a picture (sorry I don't know how to do it with Julia): 

    ```{.dot render="dot -Tsvg -o %o.svg %i" img="img/abp_diagram_example" out="path/to/img" height=128}
    digraph {
        rankdir=LR;
        input -> pandoc -> output
        pandoc -> abp -> {pandoc, diagrams}
        { rank=same; pandoc, abp }
        { rank=same; diagrams, output }
    }
    ```
`render` is the command to execute. `%i` is the name of the input file (created by abp with the content of the code block. `%o` is the name of the image (defined by `img`). `out` is the actual output directory where the image is saved.

abp defines some shortcuts (e.g. `{{dot}}` is simply `dot -Tsvg -o %o.svg %i`).

see https://cdsoft.fr/abp/#diagrams

With this mechanism abp can virtually use any script language or diagram renderer, which is not the case with pp.

**Comment by CDSoft** [comment]
A complete example using Julia:

    # Julia integration

    ## Execute a Julia script and copy its output to the document

    ```{.julia cmd=julia}
    println("Hello World!")
    ```

    ## Execute a Julia script and include the generated picture in the document

    ```{.julia render="julia %i %o" img=plot.png}
    using Plots

    x = 1:10
    y = rand(10)
    plot(x, y)
    savefig(ARGS[1])
    ```
