### ISSUE TITLE
Documentation : `raw` class

### ISSUE THREAD

**Issue by jt291** [CDSoft/abp#3]
Hello,
I'm testing `abc 0.1.8.4` and I don't see how to use the `raw` class. There is no example on [CDSoft](https://cdsoft.fr/abp/).

With the command `pandoc -f markdown -t html -F abp` and the source
```
::: raw
**hello**
:::
```
we obtain 
```
<div class="raw">
<p><strong>hello</strong></p>
</div>
```
The strings `**hello**` seem to be expanded into the block ?
I was just waiting for `**hello**`.
Thanks.

**Comment by CDSoft** [comment]
Hello,
This is the expected (yet not documented...) behavior. In fact `raw` disables abp string expansion, not pandoc.
You can for instance tell pandoc not to interpret `**`:
```
  :::
  \*\*hello\*\*
  :::
```
or use a code block:
`````
```
**hello**
```
`````

I'll try to better document the raw class.

**Comment by CDSoft** [comment]
Another example:
```
% document title

The title of the document is `{{title}}`.

It is in the title variable (`{{title}}`{.raw}).
```
becomes
```
<p>The title of the document is <code>document title</code>.</p>
<p>It is in the title variable (<code class="raw">{{title}}</code>).</p>
```

**Comment by jt291** [comment]
Thank you. I got it.
