### ISSUE TITLE
Incompatible API versions

### ISSUE THREAD

**Issue by khalid-hussain** [CDSoft/abp#7]
System: Windows 10
Pandoc: `v2.10.1`
Command: `pandoc -F abp -t docx -o draft.docx test.md`
Built using Windows.

Error:

```
abp: Error in $: Incompatible API versions: encoded with [1,21] but attempted to decode with [1,20].
CallStack (from HasCallStack):
  error, called at .\Text\Pandoc\JSON.hs:112:48 in pandoc-types-1.20-72y18aEn2T35AOODRekZAP:Text.Pandoc.JSON
Error running filter abp:
Filter returned error status 1
make: *** [docx] Error 83
```

`abp` compilation was successful:

```
Finished in 3.1949 seconds
43 examples, 0 failures

abp               > Test suite abp-test passed
Completed 14 action(s).
```

**Comment by khalid-hussain** [comment]
After some more debugging, I have found that the problem was with `test.md`.

**Comment by khalid-hussain** [comment]
I've tried it with another project and the problem seems to stem from the Pandoc version.

**Comment by CDSoft** [comment]
abp is compiled with a specific version of pandoc. It must be used with this version of pandoc.
I think running "stack install pandoc" in the abp directory will install the expected pandoc version.
